apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-world
  namespace: default
  labels:
    k8s-app: hello-world
spec:
  selector:
    matchLabels:
      k8s-app: hello-world
  endpoints:
  - port: web
    interval: 10s
  namespaceSelector:
    matchNames:
    - default
