apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox2
  labels:
    app: busybox2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox2
  template:
    metadata:
      labels:
        app: busybox2
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
          - /bin/sh
          - "-c"
          - sha1sum /dev/zero 
        imagePullPolicy: Always
      restartPolicy: Always
      dnsPolicy: ClusterFirst
