apiVersion: v1
kind: Secret
metadata:
    name: cluster-autoscaler-azure
    namespace: kube-system
data:
    ClientID: ZWQ4N2EzMGMtYzdkYS00ZTRjLTkzZGEtOWUwZTE3NzUzNjhjCg==
    ClientSecret: NTA1MGJmODMtZTNiYS00YjlhLTk0YWEtOTFjOTI3NmU0NTQyCg==
    ResourceGroup: dW5pdDRkZW1vCg==
    SubscriptionID: NTZlMDVhMTUtYWJmZi00NGRmLTkyOTctYjZiNmM1ZmNhYThlCg==
    TenantID: NzJmOTg4YmYtODZmMS00MWFmLTkxYWItMmQ3Y2QwMTFkYjQ3Cg==
    VMType: QUtTCg==
    ClusterName: dW5pdDRkZW1vCg==
    NodeResourceGroup: TUNfdW5pdDRkZW1vX3VuaXQ0ZGVtb193ZXN0ZXVyb3BlCg==
