apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: ingress-nginx-metrics
  labels:
    app: ingress-nginx-metrics
spec:
  ports:
    - name: metrics
      port: 10254
      protocol: TCP
      targetPort: 10254
  selector:
    app: ingress-nginx
