apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
type: Opaque
data:
  redisHost: {{ default "" .Values.secret.redishost | b64enc | quote }}
  redisKey: {{ default "" .Values.secret.rediskey | b64enc | quote }}
